# ===============================
# Application Configuration
# ===============================

# Local image storage directory
app.upload.image-path=uploads/images

# Support correct public URL when deployed behind a reverse proxy
server.forward-headers-strategy=framework

#this file is configuration file for your Spring Boot application.

spring.application.name=spring-boot-tutorial
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=spring_tutorial
spring.datasource.password=spring123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

#create file log
logging.file.name=logs/spring-boot.log

#Jwt token
jwt.secret=my-super-secret-key-for-jwt-token-123456789012345
jwt.expiration=3600000

#debug=true
# Hide most Spring logs
logging.level.root=WARN

# Show logs from your project
logging.level.com.example.tutorial=DEBUG

logging.level.org.flywaydb=INFO

# Hide Hibernate SQL
#spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF

# Hide Java stack trace from API error responses
server.error.include-stacktrace=never

# Hide internal exception messages from API responses
server.error.include-message=never

# Hide exception class/type from API responses
server.error.include-exception=false

# Hide validation/binding error details from default Spring error responses
server.error.include-binding-errors=never

# Maximum size for a single uploaded file
spring.servlet.multipart.max-file-size=5MB

# Maximum size for the whole multipart request
spring.servlet.multipart.max-request-size=10MB

# migration file not auto migrate until start run project again
spring.devtools.restart.exclude=db/migration/**