CREATE TABLE brands
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(255) NOT NULL,
    description    VARCHAR2(255),

    create_uid     NUMBER,
    update_uid     NUMBER,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at     TIMESTAMP,
    deleted_uid    NUMBER,
    deleted_reason VARCHAR2(500)
);